# Generated by Django 5.2.1 on 2025-05-28 09:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_page_user_page_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='page_access',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AddField(
            model_name='user',
            name='page_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('marketing', 'Marketing'), ('sales', 'Sales'), ('finance', 'Finance'), ('operations', 'Operations')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
