# Generated by Django 5.2.1 on 2025-05-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_comment'),
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='has_access',
        ),
        migrations.AddField(
            model_name='comment',
            name='has_access',
            field=models.ManyToManyField(related_name='accessible_comments', to='users.user'),
        ),
    ]
